# Generated by Django 5.2.17 on 2026-09-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=200)),
                (
                    "direction",
                    models.CharField(choices=[("in", "Cobro"), ("out", "Pago")], max_length=3),
                ),
                ("due_date", models.DateField()),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "reference"), name="unique_obligation"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outstanding_amount__gte", 0)),
                        name="positive_outstanding",
                    ),
                ],
            },
        ),
    ]
