# Generated by Django 5.2.17 on 2026-09-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auditlog"),
        ("forecast", "0003_recurrencereview"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrenceOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.company"
                    ),
                ),
                (
                    "obligation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="forecast.obligation"
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forecast.recurrencereview"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "key"), name="unique_recurrence_occurrence"
                    )
                ],
            },
        ),
    ]
