# Generated by Django 5.2.17 on 2026-10-03 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_company_liquidity_threshold"),
        ("forecast", "0005_alertevaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("method", models.CharField(max_length=32)),
                ("horizon", models.PositiveSmallIntegerField()),
                ("as_of", models.DateField()),
                ("evidence", models.JSONField()),
                ("result", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "fingerprint"), name="unique_forecast_run"
                    )
                ],
            },
        ),
    ]
