# Generated by Django 5.2.17 on 2026-10-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="liquidity_threshold",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
