import { FormEvent, useEffect, useState } from 'react';
type Entry = { id: number; created_at: string; username: string; action: string; entity: string; entity_id: string; before: Record<string, unknown>; after: Record<string, unknown> };
type Page = { count: number; next: string | null; previous: string | null; results: Entry[] };
const labels: Record<string, string> = { 'account.balance_updated': 'Saldo actualizado', 'liquidity.threshold_updated': 'Umbral actualizado', 'liquidity.evaluated': 'Evaluación guardada', 'obligation.created': 'Obligación creada', 'obligation.updated': 'Obligación actualizada', 'company.created': 'Empresa creada', 'account.updated': 'Cuenta de usuario actualizada', 'classification.rule_deleted': 'Regla eliminada', 'recurrence.review': 'Recurrencia revisada', 'recurrence.create': 'Obligación recurrente creada', 'recurrence.link': 'Recurrencia vinculada', 'recurrence.unlinked': 'Recurrencia desvinculada' };
export function AuditHistory({ company }: { company: string }) {
  const [data, setData] = useState<Page | null>(null); const [page, setPage] = useState(1); const [action, setAction] = useState(''); const [revision, setRevision] = useState(0); const [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController(); setData(null); setError('');
    fetch(`/api/companies/${company}/audit/?page=${page}&action=${encodeURIComponent(action)}`, { signal: controller.signal }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.detail || 'No se pudo consultar la auditoría.'); setData(result); }).catch(e => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [company, page, action, revision]);
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setAction(String(new FormData(event.currentTarget).get('action') || '').trim()); setPage(1); setRevision(n => n + 1); }
  return <section className="panel"><h2>Auditoría de la empresa</h2><p>Registro de los cambios auditados. Disponible para propietario y contador; no incluye todavía todos los accesos ni todas las operaciones de la aplicación.</p><form className="toolbar" onSubmit={filter}><label>Filtrar por código de acción<input name="action" maxLength={80} placeholder="Ej.: account.balance_updated" /></label><button>Consultar</button></form>{error && <p className="error" role="alert">{error}</p>}{!data && !error && <p role="status">Cargando auditoría…</p>}{data && <>{!data.count ? <p>No hay registros para este filtro.</p> : <div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Detalle</th></tr></thead><tbody>{data.results.map(row => <tr key={row.id}><td>{new Date(row.created_at).toLocaleString('es-CO')}</td><td>{row.username}</td><td>{labels[row.action] || row.action}<small>{row.action}</small></td><td><details><summary>Ver cambio · {row.entity} #{row.entity_id}</summary><p>Antes</p><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(row.before, null, 2)}</pre><p>Después</p><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(row.after, null, 2)}</pre></details></td></tr>)}</tbody></table></div>}<div className="toolbar"><button disabled={!data.previous} onClick={() => setPage(n => n - 1)}>Anterior</button><span>Página {page} · {data.count} cambios</span><button disabled={!data.next} onClick={() => setPage(n => n + 1)}>Siguiente</button></div></>}</section>;
}
