# Generated by Django 5.2.17 on 2026-09-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "currency",
                    models.CharField(choices=[("COP", "COP")], default="COP", max_length=3),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=18)),
                ("balance_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("description", models.CharField(max_length=250)),
                ("category", models.CharField(default="Otros", max_length=80)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "external_id"), name="unique_transaction"
                    )
                ],
            },
        ),
    ]
