# Generated by Django 5.2.17 on 2026-09-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0002_importjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="classification_source",
            field=models.CharField(default="existing", max_length=16),
        ),
    ]
