# Generated by Django 5.2.17 on 2026-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0003_transaction_classification_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="file_format",
            field=models.CharField(
                choices=[("csv", "CSV"), ("xlsx", "XLSX")], default="csv", max_length=4
            ),
        ),
    ]
