# Generated by Django 5.2.17 on 2026-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0004_importjob_file_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="transaction",
            name="normalized_description",
            field=models.TextField(blank=True),
        ),
    ]
