# Generated by Django 5.2.17 on 2026-10-03 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0006_normalize_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="history_complete_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="history_complete_through",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="history_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="history_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
