# Generated by Django 5.2.17 on 2026-10-03 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_company_liquidity_threshold"),
        ("banking", "0008_bankconnection_bankaccount_connection_bankconsent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("normalized_name", models.CharField(max_length=250)),
                ("display_name", models.CharField(max_length=250)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.company"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="banking.merchant",
            ),
        ),
        migrations.CreateModel(
            name="MerchantAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("normalized_name", models.CharField(max_length=250)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.company"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="banking.merchant"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="merchant",
            constraint=models.UniqueConstraint(
                fields=("company", "normalized_name"), name="unique_company_merchant"
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantalias",
            constraint=models.UniqueConstraint(
                fields=("company", "provider", "normalized_name"),
                name="unique_provider_merchant_alias",
            ),
        ),
    ]
